[package]
name = "puzzle_2-1"
version = "0.1.0"
authors = ["Hussam Alhassan <husmus7g@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
